In [95]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [96]:
# Load the dataset
dataset = pd.read_excel('images-finished.xlsx')
dataset = dataset[:100]

In [97]:
dataset

,Column1,count,actual count,hit rate,Front,Close,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,lego_shop_1,4.0,5.0,0.8,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,lego_shop_2,0.0,4.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,lego_shop_3,0.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,lego_shop_4,0.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,lego_shop_5,0.0,5.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,lego_shop_96,0.0,11.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,lego_shop_97,0.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,lego_shop_98,0.0,4.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,lego_shop_99,0.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,lego_shop_100,0.0,11.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
dataset['Log_Count'] = dataset['actual count'].apply(lambda x: np.log(x))

In [100]:
# Split the dataset into features (X) and target variable (y)
X = dataset[['Front','Close','Log_Count']]
y = dataset['hit rate']

In [101]:
X

    Front  Close  Log_Count
0     1.0    1.0   1.609438
1     0.0    0.0   1.386294
2     0.0    0.0   1.791759
3     0.0    0.0   1.791759
4     0.0    0.0   1.609438
..    ...    ...        ...
95    1.0    0.0   2.397895
96    0.0    0.0   1.791759
97    1.0    0.0   1.386294
98    1.0    0.0   1.945910
99    1.0    0.0   2.397895

[100 rows x 3 columns]

In [102]:
y

0     0.8
1     0.0
2     0.0
3     0.0
4     0.0
     ...
95    0.0
96    0.0
97    0.0
98    0.0
99    0.0
Name: hit rate, Length: 100, dtype: float64

In [103]:
# Create the linear regression model and fit it to the data
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [104]:
# Make predictions on the same data
y_pred = regressor.predict(X)

In [105]:
# Evaluate the model using R^2 score
r2 = r2_score(y, y_pred)
print("R-squared value: ", r2)

R-squared value:  0.6735930650135148

In [106]:
# Add a constant column to X
X = sm.add_constant(X)

# Fit the linear regression model
model = sm.OLS(y, X).fit()

# Print the summary table
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               hit rate   R-squared:                       0.674
Model:                            OLS   Adj. R-squared:                  0.663
Method:                 Least Squares   F-statistic:                     66.04
Date:                Wed, 10 May 2023   Prob (F-statistic):           2.97e-23
Time:                        15:11:54   Log-Likelihood:                 38.999
No. Observations:                 100   AIC:                            -70.00
Df Residuals:                      96   BIC:                            -59.58
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1043      0.076      1.363      0.176      -0.048       0.256
Front          0.1175      0.035      3.347      0.001       0.048       0.187
Close          0.6409      0.054     11.790      0.000       0.533       0.749
Log_Count     -0.0553      0.039     -1.425      0.157      -0.132       0.022
==============================================================================
Omnibus:                       35.801   Durbin-Watson:                   1.962
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               93.030
Skew:                           1.274   Prob(JB):                     6.29e-21
Kurtosis:                       6.979   Cond. No.                         11.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""